
name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: Agent-1
    steps:
    - uses: actions/checkout@v4
    - name: Set Up NodeJs
      uses: actions/setup-node@v4
      with:
        node-version: '23'
    - name: Frontend Compilation
      run: |
        cd client
        find . -name "*.js" -exec node --check {} +
    - name: Backend Compilation
      run: |
        cd api
        find . -name "*.js" -exec node --check {} +
  gitleaks-scan:
    runs-on: Agent-1
    needs: compile
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Gitleaks setup
        uses: gitleaks/gitleaks-action@v2
      - name: Gitleaks 
        run: |
          gitleaks detect --source ./client --exit-code 1
          gitleaks detect --source ./api --exit-code 1
