
name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: Agent-1
    steps:
    - uses: actions/checkout@v4
    - name: Set Up NodeJs
      uses: actions/setup-node@v4
      with:
        node-version: '23'
    - name: Frontend Compilation
      run: |
        cd client
        find . -name "*.js" -exec node --check {} +
    - name: Backend Compilation
      run: |
        cd api
        find . -name "*.js" -exec node --check {} +
  gitleaks-scan:
    runs-on: Agent-1
    needs: compile
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Gitleaks setup
        uses: gitleaks/gitleaks-action@v2
      - name: Gitleaks 
        run: |
          gitleaks detect --source ./client --exit-code 1
          gitleaks detect --source ./api --exit-code 1
  trivy-scan:
    runs-on: Agent-1
    needs: 
      - compile
      - gitleaks-scan
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Run trivy scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
  sonarqube-scan:
    runs-on: Agent-1
    needs: 
      - trivy-scan
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Sonarqube scan client
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: client
          args: >
            -Dsonar.projectKey=myorg_client
            -Dsonar.projectName=myorg_client
            -Dsonar.sources=.
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  sonarqube-scan-backend:
    runs-on: Agent-1
    needs: 
      - sonarqube-scan
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Sonarqube scan client
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: api
          args: >
            -Dsonar.projectKey=myorg_client
            -Dsonar.projectName=myorg_client
            -Dsonar.sources=.
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
            
  
